### ISSUE TITLE
Timeline controls do not show when the video fills up the whole container

### ISSUE THREAD

**Issue by DanFu09** [scanner-research/vgrid#14]
When the video fills up the whole container, the timeline controls do not show:
![Screen Shot 2019-04-30 at 2 32 20 PM](https://user-images.githubusercontent.com/4600866/56994734-d4047e80-6b54-11e9-9914-3f7f969b9d72.png)

**Comment by willcrichton** [comment]
This should have been fixed in the last commit: https://github.com/scanner-research/vgrid/commit/9870319c93c44949bd8300194c3638c687c2dae9#diff-3b15a0a506d532e79ac10c8be865ef0bR150

**Comment by DanFu09** [comment]
Ack - currently pulling from npm
