### ISSUE TITLE
Vgrid can't display some videos

### ISSUE THREAD

**Issue by DanFu09** [scanner-research/vgrid#24]
I put together a notebook visualizing bounding boxes on some of Intel's self-driving car data - notebook is [here](https://github.com/scanner-research/esperlight/blob/master/view_bboxes.ipynb) in esperlight. But for some reason, the videos won't load in Vgrid - whether they're on olimar or downloaded locally (and I've tried multiple http servers locally too, both Python and an NPM one).

This is what displays forever:
<img width="700" alt="Screen Shot 2019-05-19 at 12 29 15 AM" src="https://user-images.githubusercontent.com/4600866/57977746-29ea7a80-79cd-11e9-822b-f8024654d8c7.png">

I'm not sure why these videos aren't loading - nothing obvious shows up in the console.

**Comment by willcrichton** [comment]
If you go into inspector, click on the video element for the video, and open the link it's loading in a new tab, does that show up?

**Comment by DanFu09** [comment]
This was a problem w/ the videos and HTML5 on Chrome - fixed with a different encoding scheme.

**Comment by ra1995** [comment]
Hi, I am getting this issue for locally stored videos. I am not able to get the video frame to appear, only the bboxes are drawn. Please let me know if I there is anything I can try. Thank you.
